# Generated by Django 2.1.7 on 2019-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='series_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='series',
            field=models.ManyToManyField(to='smartsport.Series'),
        ),
    ]
